#!/bin/bash

source /opt/ros/humble/setup.bash
source ~/ydlidar_ros2_ws/install/setup.bash

ros2 launch ydlidar_ros2_driver ydlidar_launch.py \
params_file:=$HOME/ydlidar_ros2_ws/src/ydlidar_ros2_driver/params/X4.yaml

